import { useEffect, useState } from "react";
import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { ShieldCheck, Loader2, AlertCircle, Copy, Check, KeyRound, Plus, LogOut, Activity, History, Tag, Info } from "lucide-react";
import {
  getAdminSession,
  adminLogin,
  adminLogout,
  listAdminUsers,
  createAdminUser,
  revokeAdminUser,
  listAdminLoginEvents,
  listSetupTypeChangeLog,
  listAdminUserTrades,
  listAdminUserSetupTypes,
  adminUpdateTradeSetupType,
  type AdminUser,
  type LoginEvent,
  type SetupTypeChangeLogEntry,
  type AdminTrade,
} from "@/lib/admin-api";
import {
  APP_SETTINGS_QUERY_KEY,
  getAppSettings,
  updateAppSettings,
  type AppSettings,
} from "@/lib/app-settings-api";

const ADMIN_SESSION_KEY = ["admin-session"] as const;
const ADMIN_USERS_KEY = ["admin-users"] as const;
const ADMIN_LOGIN_EVENTS_KEY = ["admin-login-events"] as const;
const ADMIN_SETUP_TYPE_CHANGE_LOG_KEY = ["admin-setup-type-change-log"] as const;

interface AboutForm {
  version: string;
  tagline: string;
  description: string;
  honesty_note: string;
  bug_report_email: string;
  credit_line: string;
  privacy_policy: string;
}

/** A code just generated by create/revoke, shown once so it can be copied. */
interface RevealedCode {
  userId: number;
  code: string;
  isNew: boolean;
}

function AdminLoginForm() {
  const queryClient = useQueryClient();
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, setIsPending] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!password) return;

    setError(null);
    setIsPending(true);
    try {
      await adminLogin(password);
      queryClient.setQueryData(ADMIN_SESSION_KEY, true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Invalid password.");
    } finally {
      setIsPending(false);
    }
  }

  return (
    <div className="min-h-[100dvh] bg-background text-foreground flex flex-col items-center justify-center font-sans px-4">
      <div className="fixed top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="fixed bottom-[-10%] right-[-10%] w-[30%] h-[30%] bg-blue-500/10 rounded-full blur-[100px] pointer-events-none" />

      <div className="relative w-full max-w-sm">
        <div className="flex items-center justify-center gap-2.5 mb-10">
          <div className="w-9 h-9 rounded-lg bg-primary/20 flex items-center justify-center border border-primary/30">
            <ShieldCheck className="w-4.5 h-4.5 text-primary" />
          </div>
          <span className="font-semibold tracking-tight text-xl">Admin</span>
        </div>

        <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-8 shadow-2xl">
          <div className="flex items-center gap-3 mb-1">
            <KeyRound className="w-5 h-5 text-primary shrink-0" />
            <h1 className="text-lg font-semibold tracking-tight">Enter admin password</h1>
          </div>
          <p className="text-sm text-muted-foreground mb-7 pl-8">
            Manage journal user access codes.
          </p>

          <form onSubmit={handleSubmit} className="space-y-4">
            <input
              type="password"
              autoComplete="current-password"
              placeholder="Password"
              value={password}
              onChange={(e) => {
                setPassword(e.target.value);
                if (error) setError(null);
              }}
              disabled={isPending}
              className="w-full rounded-lg border border-border/60 bg-background/60 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary/50 transition disabled:opacity-50"
            />

            {error && (
              <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2.5 text-sm text-destructive">
                <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <button
              type="submit"
              disabled={isPending || !password}
              className="w-full flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isPending ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Verifying…
                </>
              ) : (
                "Sign in"
              )}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

function CodeReveal({ revealed, onDismiss }: { revealed: RevealedCode; onDismiss: () => void }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(revealed.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="rounded-lg border border-primary/40 bg-primary/10 p-4 mb-4">
      <p className="text-sm font-medium mb-2">
        {revealed.isNew ? "New user created" : `Code reissued for user ${revealed.userId}`} — save this now, it
        won't be shown again:
      </p>
      <div className="flex items-center gap-2">
        <code className="flex-1 rounded-md bg-background/60 border border-border/60 px-3 py-2 text-sm font-mono tracking-widest">
          {revealed.code}
        </code>
        <button
          onClick={handleCopy}
          className="shrink-0 rounded-md border border-border/60 p-2 hover:bg-accent transition"
          title="Copy code"
        >
          {copied ? <Check className="w-4 h-4 text-primary" /> : <Copy className="w-4 h-4" />}
        </button>
      </div>
      <button onClick={onDismiss} className="text-xs text-muted-foreground hover:text-foreground mt-3 transition">
        Dismiss
      </button>
    </div>
  );
}

function formatRelativeTime(iso: string): string {
  const diff = Date.now() - new Date(iso).getTime();
  const mins = Math.floor(diff / 60_000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  return `${days}d ago`;
}

function LoginEventsPanel() {
  const eventsQuery = useQuery({ queryKey: ADMIN_LOGIN_EVENTS_KEY, queryFn: listAdminLoginEvents });

  return (
    <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-6 shadow-2xl mt-4">
      <div className="flex items-center gap-2 mb-5">
        <Activity className="w-4 h-4 text-muted-foreground" />
        <h2 className="text-base font-semibold tracking-tight">Recent logins</h2>
        <span className="text-xs text-muted-foreground ml-auto">last 50</span>
      </div>

      {eventsQuery.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
      {eventsQuery.isError && <p className="text-sm text-destructive">Failed to load login events.</p>}

      {eventsQuery.data && eventsQuery.data.length === 0 && (
        <p className="text-sm text-muted-foreground">No login attempts yet.</p>
      )}

      <div className="space-y-1.5">
        {eventsQuery.data?.map((event: LoginEvent) => (
          <div
            key={event.id}
            className="flex items-center gap-3 rounded-lg border border-border/40 bg-background/30 px-3 py-2.5 text-sm"
          >
            <span
              className={`shrink-0 w-1.5 h-1.5 rounded-full ${event.success ? "bg-green-500" : "bg-destructive"}`}
              title={event.success ? "Success" : "Failed"}
            />
            <div className="min-w-0 flex-1 space-y-0.5">
              <div className="flex flex-wrap gap-x-3 gap-y-0.5 text-xs text-muted-foreground">
                <span className="font-mono">{event.ipAddress}</span>
                <span>{event.ipLocation ?? "Location unavailable"}</span>
                <span>{event.osAndBrowser ?? "Device unavailable"}</span>
              </div>
              <div className="flex flex-wrap gap-x-3 gap-y-0.5 text-[11px] text-muted-foreground/70">
                <span>{event.browserTimezone ?? "Timezone unavailable"}</span>
                <span>{event.screenResolution ?? "Resolution unavailable"}</span>
                <span>{event.userId != null ? `User ${event.userId}` : "unknown code"}</span>
                <span>{event.accessCodeUsed ?? "Code unavailable"}</span>
              </div>
            </div>
            <span className="text-xs text-muted-foreground shrink-0">
              {formatRelativeTime(event.createdAt)}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

function SetupTypeChangeLogPanel() {
  const logQuery = useQuery({
    queryKey: ADMIN_SETUP_TYPE_CHANGE_LOG_KEY,
    queryFn: listSetupTypeChangeLog,
  });

  return (
    <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-6 shadow-2xl mt-4">
      <div className="flex items-center gap-2 mb-5">
        <History className="w-4 h-4 text-muted-foreground" />
        <h2 className="text-base font-semibold tracking-tight">Setup type changes</h2>
        <span className="text-xs text-muted-foreground ml-auto">last 100</span>
      </div>

      {logQuery.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
      {logQuery.isError && <p className="text-sm text-destructive">Failed to load change log.</p>}

      {logQuery.data && logQuery.data.length === 0 && (
        <p className="text-sm text-muted-foreground">No setup type changes yet.</p>
      )}

      <div className="space-y-1.5">
        {logQuery.data?.map((entry: SetupTypeChangeLogEntry) => (
          <div
            key={entry.id}
            className="flex items-center gap-3 rounded-lg border border-border/40 bg-background/30 px-3 py-2.5 text-sm"
          >
            <span className="text-xs text-muted-foreground shrink-0 w-10">U{entry.userId}</span>
            <span className="text-xs text-muted-foreground shrink-0 truncate w-36">
              {entry.weekLabel} · T{entry.tradeNumber}
            </span>
            <span className="flex-1 text-xs text-muted-foreground truncate">
              <span className="opacity-70">{entry.oldName ?? "—"}</span>
              {" → "}
              <span>{entry.newName ?? "—"}</span>
            </span>
            <span className="text-xs text-muted-foreground shrink-0">
              {formatRelativeTime(entry.changedAt)}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

function EditAboutPanel() {
  const queryClient = useQueryClient();
  const aboutQuery = useQuery({
    queryKey: APP_SETTINGS_QUERY_KEY,
    queryFn: getAppSettings,
  });
  const [form, setForm] = useState<AboutForm>({
    version: "",
    tagline: "",
    description: "",
    honesty_note: "",
    bug_report_email: "",
    credit_line: "",
    privacy_policy: "",
  });
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!aboutQuery.data) return;
    const settings: AppSettings = aboutQuery.data;
    setForm({
      version: settings.version,
      tagline: settings.tagline,
      description: settings.description,
      honesty_note: settings.honesty_note,
      bug_report_email: settings.bug_report_email,
      credit_line: settings.credit_line ?? "",
      privacy_policy: settings.privacy_policy,
    });
  }, [aboutQuery.data]);

  const saveMutation = useMutation({
    mutationFn: updateAppSettings,
    onSuccess: (settings) => {
      queryClient.setQueryData(APP_SETTINGS_QUERY_KEY, settings);
      setSuccess(true);
      setError(null);
      setTimeout(() => setSuccess(false), 3000);
    },
    onError: (err) => {
      setSuccess(false);
      setError(err instanceof Error ? err.message : "Failed to save About content.");
    },
  });

  const inputClass =
    "w-full rounded-lg border border-border/60 bg-background/60 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary/50 transition disabled:opacity-50";
  const labelClass = "block text-xs font-medium text-muted-foreground mb-1.5";

  function updateField(field: keyof AboutForm, value: string) {
    setForm((current) => ({ ...current, [field]: value }));
    setSuccess(false);
    setError(null);
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    saveMutation.mutate(form);
  }

  return (
    <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-6 shadow-2xl mt-4">
      <div className="flex items-center gap-2 mb-5">
        <Info className="w-4 h-4 text-muted-foreground" />
        <h2 className="text-base font-semibold tracking-tight">Edit About</h2>
        <span className="text-xs text-muted-foreground ml-auto">public content</span>
      </div>

      {aboutQuery.isLoading && (
        <p className="text-sm text-muted-foreground mb-4">Loading current About content…</p>
      )}
      {aboutQuery.isError && (
        <p className="text-sm text-destructive mb-4">Failed to load current About content.</p>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className={labelClass} htmlFor="about-version">Version</label>
          <input
            id="about-version"
            value={form.version}
            onChange={(e) => updateField("version", e.target.value)}
            className={inputClass}
            disabled={aboutQuery.isLoading || saveMutation.isPending}
          />
        </div>
        <div>
          <label className={labelClass} htmlFor="about-tagline">Tagline</label>
          <input
            id="about-tagline"
            value={form.tagline}
            onChange={(e) => updateField("tagline", e.target.value)}
            className={inputClass}
            disabled={aboutQuery.isLoading || saveMutation.isPending}
          />
        </div>
        <div>
          <label className={labelClass} htmlFor="about-description">Description</label>
          <textarea
            id="about-description"
            value={form.description}
            onChange={(e) => updateField("description", e.target.value)}
            className={`${inputClass} min-h-24 resize-y`}
            disabled={aboutQuery.isLoading || saveMutation.isPending}
          />
        </div>
        <div>
          <label className={labelClass} htmlFor="about-honesty-note">Honesty Note</label>
          <textarea
            id="about-honesty-note"
            value={form.honesty_note}
            onChange={(e) => updateField("honesty_note", e.target.value)}
            className={`${inputClass} min-h-24 resize-y`}
            disabled={aboutQuery.isLoading || saveMutation.isPending}
          />
        </div>
        <div>
          <label className={labelClass} htmlFor="about-bug-report-email">Bug Report Email</label>
          <input
            id="about-bug-report-email"
            type="email"
            value={form.bug_report_email}
            onChange={(e) => updateField("bug_report_email", e.target.value)}
            className={inputClass}
            disabled={aboutQuery.isLoading || saveMutation.isPending}
          />
        </div>
        <div>
          <label className={labelClass} htmlFor="about-credit-line">Credit Line (optional)</label>
          <input
            id="about-credit-line"
            value={form.credit_line}
            onChange={(e) => updateField("credit_line", e.target.value)}
            className={inputClass}
            disabled={aboutQuery.isLoading || saveMutation.isPending}
            placeholder="Shown at the bottom of About"
          />
        </div>
        <div>
          <label className={labelClass} htmlFor="about-privacy-policy">Privacy Policy</label>
          <textarea
            id="about-privacy-policy"
            value={form.privacy_policy}
            onChange={(e) => updateField("privacy_policy", e.target.value)}
            className={`${inputClass} min-h-24 resize-y`}
            disabled={aboutQuery.isLoading || saveMutation.isPending}
          />
        </div>

        {error && (
          <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2.5 text-sm text-destructive">
            <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
            <span>{error}</span>
          </div>
        )}
        {success && (
          <div className="flex items-center gap-2 rounded-lg border border-green-500/40 bg-green-500/10 px-3 py-2.5 text-sm text-green-400">
            <Check className="w-4 h-4 shrink-0" />
            <span>About content saved.</span>
          </div>
        )}

        <button
          type="submit"
          disabled={aboutQuery.isLoading || aboutQuery.isError || saveMutation.isPending}
          className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {saveMutation.isPending && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
          Save
        </button>
      </form>
    </div>
  );
}

function SetupTypeReassignPanel({ users }: { users: AdminUser[] }) {
  const queryClient = useQueryClient();
  const [selectedUserId, setSelectedUserId] = useState<number | "">("");
  const [selectedTradeId, setSelectedTradeId] = useState<number | "">("");
  const [selectedNewSetupTypeId, setSelectedNewSetupTypeId] = useState<string>("null");
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const userId = selectedUserId !== "" ? selectedUserId : null;

  const tradesQuery = useQuery({
    queryKey: ["admin-user-trades", userId],
    queryFn: () => listAdminUserTrades(userId!),
    enabled: userId !== null,
  });

  const setupTypesQuery = useQuery({
    queryKey: ["admin-user-setup-types", userId],
    queryFn: () => listAdminUserSetupTypes(userId!),
    enabled: userId !== null,
  });

  const reassignMutation = useMutation({
    mutationFn: ({ tradeId, newSetupTypeId }: { tradeId: number; newSetupTypeId: number | null }) =>
      adminUpdateTradeSetupType(tradeId, newSetupTypeId),
    onSuccess: () => {
      setError(null);
      setSuccess(true);
      setSelectedTradeId("");
      setSelectedNewSetupTypeId("null");
      queryClient.invalidateQueries({ queryKey: ADMIN_SETUP_TYPE_CHANGE_LOG_KEY });
      // Also invalidate trades cache so the same user's list reflects the new assignment
      queryClient.invalidateQueries({ queryKey: ["admin-user-trades", userId] });
      setTimeout(() => setSuccess(false), 3000);
    },
    onError: (err) => {
      setSuccess(false);
      setError(err instanceof Error ? err.message : "Failed to update setup type.");
    },
  });

  function handleUserChange(value: string) {
    setSelectedUserId(value === "" ? "" : Number(value));
    setSelectedTradeId("");
    setSelectedNewSetupTypeId("null");
    setError(null);
    setSuccess(false);
  }

  function handleReassign() {
    if (selectedTradeId === "") return;
    const newSetupTypeId = selectedNewSetupTypeId === "null" ? null : Number(selectedNewSetupTypeId);
    reassignMutation.mutate({ tradeId: selectedTradeId as number, newSetupTypeId });
  }

  const selectClass =
    "w-full rounded-lg border border-border/60 bg-background/60 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary/50 transition disabled:opacity-50";

  return (
    <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-6 shadow-2xl mt-4">
      <div className="flex items-center gap-2 mb-5">
        <Tag className="w-4 h-4 text-muted-foreground" />
        <h2 className="text-base font-semibold tracking-tight">Reassign setup type</h2>
        <span className="text-xs text-muted-foreground ml-auto">admin only</span>
      </div>

      <div className="space-y-3">
        {/* Step 1: pick a user */}
        <select value={selectedUserId} onChange={(e) => handleUserChange(e.target.value)} className={selectClass}>
          <option value="">— Select a user —</option>
          {users.map((u) => (
            <option key={u.id} value={u.id}>
              User {u.id} ({u.tradeCount} {u.tradeCount === 1 ? "trade" : "trades"})
            </option>
          ))}
        </select>

        {/* Step 2: pick a trade (visible once a user is selected) */}
        {userId !== null && (
          <>
            {tradesQuery.isLoading && (
              <p className="text-sm text-muted-foreground">Loading trades…</p>
            )}
            {tradesQuery.isError && (
              <p className="text-sm text-destructive">Failed to load trades.</p>
            )}
            {tradesQuery.data && tradesQuery.data.length === 0 && (
              <p className="text-sm text-muted-foreground">No trades for this user.</p>
            )}

            {tradesQuery.data && tradesQuery.data.length > 0 && (
              <>
                <select
                  value={selectedTradeId}
                  onChange={(e) => {
                    setSelectedTradeId(e.target.value === "" ? "" : Number(e.target.value));
                    setError(null);
                    setSuccess(false);
                  }}
                  className={selectClass}
                >
                  <option value="">— Select a trade —</option>
                  {tradesQuery.data.map((t: AdminTrade) => (
                    <option key={t.id} value={t.id}>
                      {t.weekLabel} · T{t.tradeNumber} · {t.result}
                      {t.archivedAt ? " [archived]" : ""}
                      {t.setupTypeName ? ` · ${t.setupTypeName}` : ""}
                    </option>
                  ))}
                </select>

                {/* Step 3: pick the new setup type */}
                <select
                  value={selectedNewSetupTypeId}
                  onChange={(e) => {
                    setSelectedNewSetupTypeId(e.target.value);
                    setError(null);
                    setSuccess(false);
                  }}
                  className={selectClass}
                  disabled={setupTypesQuery.isLoading}
                >
                  <option value="null">— Clear (no setup type) —</option>
                  {setupTypesQuery.data?.map((st) => (
                    <option key={st.id} value={st.id}>
                      {st.name}{!st.active ? " (inactive)" : ""}
                    </option>
                  ))}
                </select>

                {error && (
                  <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2.5 text-sm text-destructive">
                    <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                    <span>{error}</span>
                  </div>
                )}

                {success && (
                  <div className="flex items-center gap-2 rounded-lg border border-green-500/40 bg-green-500/10 px-3 py-2.5 text-sm text-green-400">
                    <Check className="w-4 h-4 shrink-0" />
                    <span>Setup type updated.</span>
                  </div>
                )}

                <button
                  onClick={handleReassign}
                  disabled={selectedTradeId === "" || reassignMutation.isPending}
                  className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {reassignMutation.isPending ? (
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  ) : (
                    <Tag className="w-3.5 h-3.5" />
                  )}
                  Update
                </button>
              </>
            )}
          </>
        )}
      </div>
    </div>
  );
}

function AdminPanel() {
  const queryClient = useQueryClient();
  const [revealed, setRevealed] = useState<RevealedCode | null>(null);
  const [error, setError] = useState<string | null>(null);

  const usersQuery = useQuery({ queryKey: ADMIN_USERS_KEY, queryFn: listAdminUsers });

  const createMutation = useMutation({
    mutationFn: createAdminUser,
    onSuccess: (user: AdminUser & { code: string }) => {
      setError(null);
      setRevealed({ userId: user.id, code: user.code, isNew: true });
      queryClient.invalidateQueries({ queryKey: ADMIN_USERS_KEY });
    },
    onError: (err) => setError(err instanceof Error ? err.message : "Failed to create user."),
  });

  const revokeMutation = useMutation({
    mutationFn: revokeAdminUser,
    onSuccess: (result) => {
      setError(null);
      setRevealed({ userId: result.id, code: result.code, isNew: false });
    },
    onError: (err) => setError(err instanceof Error ? err.message : "Failed to revoke access code."),
  });

  async function handleLogout() {
    await adminLogout();
    queryClient.setQueryData(ADMIN_SESSION_KEY, false);
  }

  return (
    <div className="min-h-[100dvh] bg-background text-foreground font-sans px-4 py-10">
      <div className="max-w-2xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-lg bg-primary/20 flex items-center justify-center border border-primary/30">
              <ShieldCheck className="w-4.5 h-4.5 text-primary" />
            </div>
            <span className="font-semibold tracking-tight text-xl">Admin</span>
          </div>
          <button
            onClick={handleLogout}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition"
          >
            <LogOut className="w-4 h-4" />
            Sign out
          </button>
        </div>

        {revealed && <CodeReveal revealed={revealed} onDismiss={() => setRevealed(null)} />}

        {error && (
          <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2.5 text-sm text-destructive mb-4">
            <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-6 shadow-2xl">
          <div className="flex items-center justify-between mb-5">
            <h2 className="text-base font-semibold tracking-tight">Users</h2>
            <button
              onClick={() => createMutation.mutate()}
              disabled={createMutation.isPending}
              className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 active:scale-[0.98] disabled:opacity-50"
            >
              {createMutation.isPending ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Plus className="w-3.5 h-3.5" />
              )}
              New user
            </button>
          </div>

          {usersQuery.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
          {usersQuery.isError && <p className="text-sm text-destructive">Failed to load users.</p>}

          {usersQuery.data && usersQuery.data.length === 0 && (
            <p className="text-sm text-muted-foreground">No users yet.</p>
          )}

          <div className="space-y-2">
            {usersQuery.data?.map((user) => (
              <div
                key={user.id}
                className="flex items-center justify-between rounded-lg border border-border/50 bg-background/40 px-4 py-3"
              >
                <div>
                  <p className="text-sm font-medium">
                    User {user.id}{user.nickname ? ` (${user.nickname})` : ""}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Created {new Date(user.createdAt).toLocaleDateString()}
                  </p>
                  <div className="flex items-center gap-3 mt-1">
                    <span className="text-xs text-muted-foreground">
                      {user.weekCount} {user.weekCount === 1 ? "week" : "weeks"}
                    </span>
                    <span className="text-xs text-muted-foreground">·</span>
                    <span className="text-xs text-muted-foreground">
                      {user.tradeCount} {user.tradeCount === 1 ? "trade" : "trades"}
                    </span>
                    {user.lastActivity && (
                      <>
                        <span className="text-xs text-muted-foreground">·</span>
                        <span className="text-xs text-muted-foreground">
                          active {formatRelativeTime(user.lastActivity)}
                        </span>
                      </>
                    )}
                  </div>
                </div>
                <button
                  onClick={() => revokeMutation.mutate(user.id)}
                  disabled={revokeMutation.isPending}
                  className="text-sm rounded-lg border border-border/60 px-3 py-1.5 hover:bg-accent transition disabled:opacity-50"
                >
                  Revoke &amp; reissue
                </button>
              </div>
            ))}
          </div>
        </div>

        <EditAboutPanel />
        <LoginEventsPanel />
        <SetupTypeChangeLogPanel />
        <SetupTypeReassignPanel users={usersQuery.data ?? []} />
      </div>
    </div>
  );
}

export function AdminPage() {
  const sessionQuery = useQuery({ queryKey: ADMIN_SESSION_KEY, queryFn: getAdminSession });

  if (sessionQuery.isLoading) return null;
  if (!sessionQuery.data) return <AdminLoginForm />;
  return <AdminPanel />;
}
