import { useState } from "react";
import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { ShieldCheck, Loader2, AlertCircle, Copy, Check, KeyRound, Plus, LogOut } from "lucide-react";
import {
  getAdminSession,
  adminLogin,
  adminLogout,
  listAdminUsers,
  createAdminUser,
  revokeAdminUser,
  type AdminUser,
} from "@/lib/admin-api";

const ADMIN_SESSION_KEY = ["admin-session"] as const;
const ADMIN_USERS_KEY = ["admin-users"] as const;

/** A code just generated by create/revoke, shown once so it can be copied. */
interface RevealedCode {
  userId: number;
  code: string;
  isNew: boolean;
}

function AdminLoginForm() {
  const queryClient = useQueryClient();
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isPending, setIsPending] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!password) return;

    setError(null);
    setIsPending(true);
    try {
      await adminLogin(password);
      queryClient.setQueryData(ADMIN_SESSION_KEY, true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Invalid password.");
    } finally {
      setIsPending(false);
    }
  }

  return (
    <div className="min-h-[100dvh] bg-background text-foreground flex flex-col items-center justify-center font-sans px-4">
      <div className="fixed top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="fixed bottom-[-10%] right-[-10%] w-[30%] h-[30%] bg-blue-500/10 rounded-full blur-[100px] pointer-events-none" />

      <div className="relative w-full max-w-sm">
        <div className="flex items-center justify-center gap-2.5 mb-10">
          <div className="w-9 h-9 rounded-lg bg-primary/20 flex items-center justify-center border border-primary/30">
            <ShieldCheck className="w-4.5 h-4.5 text-primary" />
          </div>
          <span className="font-semibold tracking-tight text-xl">Admin</span>
        </div>

        <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-8 shadow-2xl">
          <div className="flex items-center gap-3 mb-1">
            <KeyRound className="w-5 h-5 text-primary shrink-0" />
            <h1 className="text-lg font-semibold tracking-tight">Enter admin password</h1>
          </div>
          <p className="text-sm text-muted-foreground mb-7 pl-8">
            Manage journal user access codes.
          </p>

          <form onSubmit={handleSubmit} className="space-y-4">
            <input
              type="password"
              autoComplete="current-password"
              placeholder="Password"
              value={password}
              onChange={(e) => {
                setPassword(e.target.value);
                if (error) setError(null);
              }}
              disabled={isPending}
              className="w-full rounded-lg border border-border/60 bg-background/60 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary/50 transition disabled:opacity-50"
            />

            {error && (
              <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2.5 text-sm text-destructive">
                <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <button
              type="submit"
              disabled={isPending || !password}
              className="w-full flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isPending ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Verifying…
                </>
              ) : (
                "Sign in"
              )}
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}

function CodeReveal({ revealed, onDismiss }: { revealed: RevealedCode; onDismiss: () => void }) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(revealed.code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="rounded-lg border border-primary/40 bg-primary/10 p-4 mb-4">
      <p className="text-sm font-medium mb-2">
        {revealed.isNew ? "New user created" : `Code reissued for user ${revealed.userId}`} — save this now, it
        won't be shown again:
      </p>
      <div className="flex items-center gap-2">
        <code className="flex-1 rounded-md bg-background/60 border border-border/60 px-3 py-2 text-sm font-mono tracking-widest">
          {revealed.code}
        </code>
        <button
          onClick={handleCopy}
          className="shrink-0 rounded-md border border-border/60 p-2 hover:bg-accent transition"
          title="Copy code"
        >
          {copied ? <Check className="w-4 h-4 text-primary" /> : <Copy className="w-4 h-4" />}
        </button>
      </div>
      <button onClick={onDismiss} className="text-xs text-muted-foreground hover:text-foreground mt-3 transition">
        Dismiss
      </button>
    </div>
  );
}

function AdminPanel() {
  const queryClient = useQueryClient();
  const [revealed, setRevealed] = useState<RevealedCode | null>(null);
  const [error, setError] = useState<string | null>(null);

  const usersQuery = useQuery({ queryKey: ADMIN_USERS_KEY, queryFn: listAdminUsers });

  const createMutation = useMutation({
    mutationFn: createAdminUser,
    onSuccess: (user: AdminUser & { code: string }) => {
      setError(null);
      setRevealed({ userId: user.id, code: user.code, isNew: true });
      queryClient.invalidateQueries({ queryKey: ADMIN_USERS_KEY });
    },
    onError: (err) => setError(err instanceof Error ? err.message : "Failed to create user."),
  });

  const revokeMutation = useMutation({
    mutationFn: revokeAdminUser,
    onSuccess: (result) => {
      setError(null);
      setRevealed({ userId: result.id, code: result.code, isNew: false });
    },
    onError: (err) => setError(err instanceof Error ? err.message : "Failed to revoke access code."),
  });

  async function handleLogout() {
    await adminLogout();
    queryClient.setQueryData(ADMIN_SESSION_KEY, false);
  }

  return (
    <div className="min-h-[100dvh] bg-background text-foreground font-sans px-4 py-10">
      <div className="max-w-2xl mx-auto">
        <div className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-lg bg-primary/20 flex items-center justify-center border border-primary/30">
              <ShieldCheck className="w-4.5 h-4.5 text-primary" />
            </div>
            <span className="font-semibold tracking-tight text-xl">Admin</span>
          </div>
          <button
            onClick={handleLogout}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition"
          >
            <LogOut className="w-4 h-4" />
            Sign out
          </button>
        </div>

        {revealed && <CodeReveal revealed={revealed} onDismiss={() => setRevealed(null)} />}

        {error && (
          <div className="flex items-start gap-2 rounded-lg border border-destructive/40 bg-destructive/10 px-3 py-2.5 text-sm text-destructive mb-4">
            <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-xl p-6 shadow-2xl">
          <div className="flex items-center justify-between mb-5">
            <h2 className="text-base font-semibold tracking-tight">Users</h2>
            <button
              onClick={() => createMutation.mutate()}
              disabled={createMutation.isPending}
              className="flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-sm font-semibold text-primary-foreground transition hover:bg-primary/90 active:scale-[0.98] disabled:opacity-50"
            >
              {createMutation.isPending ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Plus className="w-3.5 h-3.5" />
              )}
              New user
            </button>
          </div>

          {usersQuery.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
          {usersQuery.isError && <p className="text-sm text-destructive">Failed to load users.</p>}

          {usersQuery.data && usersQuery.data.length === 0 && (
            <p className="text-sm text-muted-foreground">No users yet.</p>
          )}

          <div className="space-y-2">
            {usersQuery.data?.map((user) => (
              <div
                key={user.id}
                className="flex items-center justify-between rounded-lg border border-border/50 bg-background/40 px-4 py-3"
              >
                <div>
                  <p className="text-sm font-medium">User {user.id}</p>
                  <p className="text-xs text-muted-foreground">
                    Created {new Date(user.createdAt).toLocaleDateString()}
                  </p>
                </div>
                <button
                  onClick={() => revokeMutation.mutate(user.id)}
                  disabled={revokeMutation.isPending}
                  className="text-sm rounded-lg border border-border/60 px-3 py-1.5 hover:bg-accent transition disabled:opacity-50"
                >
                  Revoke &amp; reissue
                </button>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export function AdminPage() {
  const sessionQuery = useQuery({ queryKey: ADMIN_SESSION_KEY, queryFn: getAdminSession });

  if (sessionQuery.isLoading) return null;
  if (!sessionQuery.data) return <AdminLoginForm />;
  return <AdminPanel />;
}
